intel/he-toolkit

.github/workflows/github-ci.yml

Added a self hosted runner for testing on specific hardware.

Add self-hosted runner for GitHub Actions

---

he-samples/cmake/seal.cmake

Solves Issue #20 
Update HE-Toolkit to use the latest release of SEAL v3.6.6

Update SEAL version to v3.6.6

---

docker/README.md
he-samples/examples/psi/psi.cpp

Bug fix for PSI example. Errors thrown from HElib are now caught and handled appropriately by the PSI example program.
Additional information has been added to the docker README specifying possible additional steps required to build the docker container on MacOS.

Simple PSI example bug fix

---

kit/command_init.py
tests/test_cmd_init.py
tests/test_integration_init.py

hekit should create the default config file instead of create it.

hekit init creates default config file

---

hekit
kit/commands/init.py

Fix error about only run hekit from the toolkit dir

Fix ModuleNotFoundError

---

.github/workflows/github-ci.yml
he-samples/examples/logistic-regression/datasets/generate_data.py
he-samples/examples/logistic-regression/datasets/lr_base.py
kit/commands/check_deps.py
kit/commands/docker_build.py
kit/commands/init.py
kit/commands/list_cmd.py
kit/tools/healg.py
kit/utils/component_builder.py
kit/utils/spec.py

Changes after updating black to version 22.6.0

Black code style v22.6.0

---

README.md
docker/which-files.txt
kit/PLUGINS.md
kit/README.md

Documentation regarding 3rd-party plugins.

Plugins docs

---

README.md
docker/README.md

Additional known issues added to the documentation.
Extra hints/prompts to useful hekit commands from the main README.

Additional documentation

---

kit/README.md
kit/hekit.py
tests/test_integration_check_deps.py
tests/test_integration_docker.py
tests/test_integration_init.py
tests/test_integration_install.py
tests/test_integration_wrong_inputs.py

Global option 
Enables stack trace of error of unexpected errors for easier debugging
Docs update
Test that the toggle works

debug mode

---

he-samples/examples/logistic-regression/datasets/CMakeLists.txt

fixed Cmake python version comparison

fixed python version

---

README.md
docker/which-files.txt
hekit
kit/PLUGINS.md
kit/README.md
kit/commands/plugin.py
kit/hekit.py
kit/utils/files.py
kit/utils/subparsers.py
tests/test_integration_healg.py
third-party/README.md
third-party/hello_world_plugin/hello.py
third-party/hello_world_plugin/plugin.toml
third-party/hello_world_plugin/start.py

Example plugin for learning and rapid development

hello plugin

---

kit/commands/init.py
tests/test_cmd_init.py
tests/test_integration_init.py

Add an option  asking the user if they would like to edit their configuration file. If not then we can tell the user what lines they need to add.

Add option of editing the .bashrc

---

.github/workflows/github-ci.yml
kit/commands/init.py

hekit command can be run from locations other than he-toolkit root dir.

(CI) Test hekit can be run from anywhere

---

.pre-commit-config.yaml
deployments/config_psi/scripts/decode.py
deployments/config_psi/scripts/encode.py
docker/Dockerfile.toolkit
kit/utils/docker_tools.py
kit/utils/files.py

Fixed a bug in the docker build where the `hekit init` command expects user input.

Bug fix docker build

---

deployments/config_psi/scripts/decode.py
deployments/config_psi/scripts/natural.py

Co-authored-by: Jack Crawford <jack.crawford@intel.com>

fix to decoder

---

.github/workflows/README.md
.github/workflows/github-ci.yml

Added python version 3.9 on Ubuntu 20.04 and python version 3.10 on Ubuntu 22.04

add python 3.9 to ci

---

docker/Dockerfile.base

clang-format was missing from the base dockerfile
Describe the big picture of your changes here to communicate to the maintainers
why we should accept this pull request. If it fixes a bug or resolves a feature
request, be sure to link to that issue.
What types of changes does your code introduce to the HE Toolkit project?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you are unsure about any of them, do not hesitate to ask. We are
here to help! This is simply a reminder of what we are going to look for before
merging your code._
If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did, what alternatives you
considered, etc.

added clang-format to Dockerfile.base

---

kit/commands/docker_build.py

Small bug fix on the final printout from the `docker-build` command. It should now print the correct tag for the final image built.
What types of changes does your code introduce to the HE Toolkit project?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you are unsure about any of them, do not hesitate to ask. We are
here to help! This is simply a reminder of what we are going to look for before
merging your code._
If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did, what alternatives you
considered, etc.

Fix docker-build printout

---

docker/Dockerfile.base
docker/Dockerfile.toolkit

Bugfix in Dockerfile where docker was not picking up the `python` command.
What types of changes does your code introduce to the HE Toolkit project?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you are unsure about any of them, do not hesitate to ask. We are
here to help! This is simply a reminder of what we are going to look for before
merging your code._
If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did, what alternatives you
considered, etc.

Bugfix in Dockerfiles

---

he-samples/examples/logistic-regression/datasets/requirements.txt

Fix for CVE-2024-5206
What types of changes does your code introduce to the HE Toolkit project?
_Put an `x` in the boxes that apply_
- [ x] Bugfix (non-breaking change which fixes an issue)
_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you are unsure about any of them, do not hesitate to ask. We are
here to help! This is simply a reminder of what we are going to look for before
merging your code._
- [ x] I have read the [CONTRIBUTING](https://github.com/intel/he-toolkit/tree/main#contributing) section
N/A

Fix for CVE-2024-5206
